#!/bin/bash

## Connection
IP="192.168.1.82"
USER="root"
SSH_ARGS=""
RSYNC_ARGS_SSH=""
RSYNC_ARGS=""
RSYNC_REMOTE_PATH=""

## CROSS COMPILING ARCHITECTURES
ARCH="arm64"
CROSS_COMPILE="aarch64-linux-gnu-"

## Boot Sources Configuration
BOOTCMD_CONFIG=""
DTS_CONFIG="omnv"

## COMPONENTS ##
# QEMU
QEMU_BUILD="n"

# ATF
ATF_BUILD="n"
ATF_COMPILE_ARGS=""
ATF_PATCH_ARGS=""
ATF_REPOSITORY="https://github.com/DanieleOttaviano/arm-trusted-firmware.git"
ATF_BRANCH="master"
ATF_COMMIT=""
ATF_CONFIG=""

# U-BOOT 
UBOOT_BUILD="n"
UPD_UBOOT_COMPILE_ARGS=""
UBOOT_COMPILE_ARGS=""
UBOOT_PATCH_ARGS=""
UBOOT_REPOSITORY="https://github.com/Xilinx/u-boot-xlnx.git"
UBOOT_BRANCH="xlnx_rebase_v2022.01"
UBOOT_COMMIT=""
UBOOT_CONFIG=""

# LINUX
LINUX_BUILD="n"
UPD_LINUX_COMPILE_ARGS=""
LINUX_COMPILE_ARGS="-m"
LINUX_PATCH_ARGS="-d jailhouse_enable" 
LINUX_REPOSITORY="https://github.com/Xilinx/linux-xlnx.git"
LINUX_BRANCH="xlnx_rebase_v6.1_LTS"
LINUX_COMMIT=""
LINUX_CONFIG="omnv"

# BUILDROOT
BUILDROOT_BUILD="y"
UPD_BUILDROOT_COMPILE_ARGS=""
BUILDROOT_COMPILE_ARGS=""
BUILDROOT_PATCH_ARGS=""
BUILDROOT_REPOSITORY="https://github.com/buildroot/buildroot.git"
BUILDROOT_BRANCH="2023.05.x"
BUILDROOT_COMMIT="25d59c073ac355d5b499a9db5318fb4dc14ad56c"
BUILDROOT_CONFIG=""

# JAILHOUSE
JAILHOUSE_BUILD="n"
UPD_JAILHOUSE_COMPILE_ARGS=""
JAILHOUSE_COMPILE_ARGS="-n -r all"
JAILHOUSE_PATCH_ARGS=""
JAILHOUSE_REPOSITORY="https://github.com/DanieleOttaviano/jailhouse.git"
JAILHOUSE_BRANCH="master"
JAILHOUSE_COMMIT=""
JAILHOUSE_CONFIG="omnv"

# BOOTGEN
BOOTGEN_BUILD="n"
BOOTGEN_COMPILE_ARGS=""
BOOTGEN_PATCH_ARGS=""
BOOTGEN_REPOSITORY="https://github.com/Xilinx/bootgen.git"
BOOTGEN_BRANCH="xlnx_rel_v2022.1"
BOOTGEN_COMMIT="c77d7998d0db56f8a19642275e061b308bc24d53"
BOOTGEN_CONFIG=""
