#!/bin/bash

## QEMU TAP MODE
IP="127.0.0.1"
USER="root"
SSH_ARGS="-p 2222"
RSYNC_ARGS_SSH="ssh -p 2222"
RSYNC_ARGS="-e"
RSYNC_REMOTE_PATH=""


## CROSS COMPILING ARCHITECTURES
ARCH="arm64"
CROSS_COMPILE="aarch64-linux-gnu-"

## Boot Sources Configuration
BOOTCMD_CONFIG=""
DTS_CONFIG="omnv"

## COMPONENTS ##
# QEMU
QEMU_BUILD="y"
QEMU_COMPILE_ARGS=""
QEMU_PATCH_ARGS=""
QEMU_REPOSITORY="https://github.com/Xilinx/qemu.git"
QEMU_BRANCH="xlnx_rel_v2024.2"
QEMU_COMMIT=""
QEMU_CONFIG=""

# ATF
ATF_BUILD="y"
ATF_COMPILE_ARGS=""
ATF_PATCH_ARGS=""
ATF_REPOSITORY="https://github.com/DanieleOttaviano/arm-trusted-firmware.git"
ATF_BRANCH="master"
ATF_COMMIT=""
ATF_CONFIG=""

# U-BOOT 
UBOOT_BUILD="n"

# LINUX
LINUX_BUILD="y"
UPD_LINUX_COMPILE_ARGS=""
LINUX_COMPILE_ARGS="-m -n"
LINUX_PATCH_ARGS="-d preempt_rt, jailhouse_enable"
LINUX_REPOSITORY="https://github.com/Xilinx/linux-xlnx.git"
LINUX_BRANCH="xlnx_rebase_v6.1_LTS"
LINUX_COMMIT="846ca23fed2afa1733eea745b80b5bc98011030b"
LINUX_CONFIG=""

# BUILDROOT
BUILDROOT_BUILD="y"
UPD_BUILDROOT_COMPILE_ARGS=""
BUILDROOT_COMPILE_ARGS=""
BUILDROOT_PATCH_ARGS=""
BUILDROOT_REPOSITORY="https://github.com/buildroot/buildroot.git"
BUILDROOT_BRANCH="2023.05.x"
BUILDROOT_COMMIT="25d59c073ac355d5b499a9db5318fb4dc14ad56c"
BUILDROOT_CONFIG=""

# JAILHOUSE
JAILHOUSE_BUILD="y"
UPD_JAILHOUSE_COMPILE_ARGS=""
JAILHOUSE_COMPILE_ARGS="-n -r armr5"
JAILHOUSE_PATCH_ARGS=""
JAILHOUSE_REPOSITORY="https://github.com/DanieleOttaviano/jailhouse.git"
JAILHOUSE_BRANCH="master"
JAILHOUSE_COMMIT=""
JAILHOUSE_CONFIG="omnv"

# BOOTGEN
BOOTGEN_BUILD="n"
